### ISSUE TITLE
Output program

### ISSUE THREAD

**Issue by help-me-please-i-beg-u** [Cpavrai/haskell-evalexpr#3]
Hi,

When i launch this with ./funEvalExpr {1+1} or ./funEvalExpr "1+1", the output is respectively "{1+1}" or "1+1".

What is wrong?

**Comment by Cpavrai** [comment]
You need to write with space between each elements (operator or number). An improve would be to permit to not put space between each elements.

At this moment, the way is to write ```./funEvalExpr "1 + 1"```
